/* eslint-disable @typescript-eslint/no-require-imports -- Node TypeScript route harness. */
const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const Module=require('node:module');const ts=require('typescript');const {NextRequest}=require('next/server');
function load(file,mocks={}){const m=new Module(path.resolve(file),module);m.filename=path.resolve(file);m.paths=module.paths;m.require=n=>mocks[n]??require(n);m._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,m.filename);return m.exports;}
const access=load('src/lib/recruiter-access.ts');let result=true,error=null,calls=[];
const route=load('src/app/api/auth/recruiter/route.ts',{'@/lib/recruiter-access':access,'@supabase/supabase-js':{createClient:()=>({rpc:async(name,args)=>{calls.push({name,args});return {data:result,error};}})}});
function reset(){Object.assign(process.env,{ENABLE_RECRUITER_PAGE:'true',RECRUITER_ACCESS_CODE:'01234',RECRUITER_SESSION_SECRET:'a'.repeat(64),APP_ORIGIN:'https://example.test',NEXT_PUBLIC_SUPABASE_URL:'https://example.supabase.co',SUPABASE_SERVICE_ROLE_KEY:'test-private',VERCEL:'1'});result=true;error=null;calls=[];}
function post(body='code=01234',origin='https://example.test'){return route.POST(new NextRequest('https://example.test/api/auth/recruiter',{method:'POST',headers:{origin,'content-type':'application/x-www-form-urlencoded','x-forwarded-for':'192.0.2.1'},body}));}
test('signed sessions expire, reject tampering, and are invalidated by code rotation',()=>{reset();const config=access.recruiterConfig(),now=Date.now(),token=access.issueRecruiterSession(config,now);assert.equal(access.validRecruiterSession(token,config,now),true);assert.equal(access.validRecruiterSession(token+'x',config,now),false);assert.equal(access.validRecruiterSession(token,config,now+14400000),false);assert.equal(access.validRecruiterSession(token,{...config,code:'98765'},now),false);assert.equal(access.validRecruiterSession(token,null,now),false);});
test('gate fails closed on disabled or malformed config',async()=>{reset();process.env.ENABLE_RECRUITER_PAGE='false';assert.match((await post()).headers.get('location'),/unavailable/);assert.equal(calls.length,0);reset();process.env.RECRUITER_SESSION_SECRET='short';assert.equal(access.recruiterConfig(),null);});
test('bad origin and oversized input cannot authenticate',async()=>{reset();assert.equal((await post(undefined,'https://evil.test')).status,403);assert.match((await post('x'.repeat(257))).headers.get('location'),/invalid/);assert.equal(calls.length,0);});
test('limiter runs before matching credentials and fails closed',async()=>{reset();result=false;let r=await post();assert.match(r.headers.get('location'),/limited/);assert.equal(r.headers.get('set-cookie'),null);assert.equal(calls.length,1);reset();error={message:'private failure'};r=await post();assert.match(r.headers.get('location'),/unavailable/);assert.equal(r.headers.get('set-cookie'),null);});
test('wrong code consumes an attempt without creating a session',async()=>{reset();let r=await post('code=99999');assert.match(r.headers.get('location'),/invalid/);assert.equal(calls.length,1);assert.equal(r.headers.get('set-cookie'),null);});
test('leading-zero code opens presentation-only HttpOnly cookie',async()=>{reset();const r=await post();assert.equal(r.status,303);assert.equal(r.headers.get('location'),'https://example.test/recruiter');const cookie=r.headers.get('set-cookie');assert.match(cookie,/HttpOnly/);assert.match(cookie,/Secure/);assert.match(cookie,/Path=\/recruiter/);assert.doesNotMatch(cookie,/sb-.*auth-token/);assert.equal(r.headers.get('cache-control'),'no-store');assert.match(calls[0].args.client_bucket,/^[a-f0-9]{64}$/);assert.ok(!JSON.stringify(calls).includes('192.0.2.1'));});
test('logout expires recruiter cookie without Supabase access',async()=>{reset();const r=await post('action=logout');assert.match(r.headers.get('set-cookie'),/Max-Age=0/);assert.equal(calls.length,0);});
